- docs/make.jl
- docs/src/background/LowStorageRungeKutta.md
- docs/src/background/MultirateRungeKutta.md
- docs/src/background/StrongStabilityPreservingRungeKutta.md
- src/RungeKuttaMethods/LowStorageRungeKuttaMethods.jl
- src/RungeKuttaMethods/MultirateRungeKuttaMethods.jl
- src/TimeMachine.jl
- src/functions.jl
- src/integrators.jl
- test/basic.jl
- test/problems.jl
- test/utils.jl
still need to figure out convergence
> multirate stuff

- .github/workflows/DocCleanup.yml
- docs/make.jl
https://github.com/CliMA/ClimateMachine.jl/issues/1665
> Experiment with cleaning up gh-pages history

- test/callbacks.jl
- test/runtests.jl
> enable tests for callbacks

- .github/workflows/Documentation.yml
- .github/workflows/UnitTests.yml
- .gitignore
- Project.toml
- docs/Manifest.toml
- docs/Project.toml
- docs/make.jl
- src/functions.jl
- src/solvers/ssprk.jl
- test/basic.jl
- test/problems.jl
Part of https://github.com/CliMA/ClimaCore.jl/issues/612
> Define SSPRK methods with ForwardEulerODEFunction

- src/operators.jl
Fixes #31
I can't remember the exact context of this...
> isconst => isconstant

- test/Project.toml
This PR removes the BenchmarkTools from the pkg dep.
> Remove BenchmarkTools dep

- test/runtests.jl
- test/single_column_ARS_test.jl
Add a single column test for ARS343 
Co-authored by: @valeriabarra 
(Clearly and concisely state the purpose of this PR)
(State concisely the benefits to be derived from and the risks associated with this PR)
(Provide references to any link issues. Use closes #issuenum to automatically close an open issue)
- Fixes #
- Closes #
> add ARS343 single column test

- Project.toml
> Tag release

- test/Project.toml
- test/aqua.jl
- test/runtests.jl
This PR adds some Aqua tests for:
- Unbound type parameters
- Method ambiguities
> Add Aqua tests

- Project.toml
> Bump version to 0.2.6

- docs/make.jl
- docs/src/algorithms.md
- docs/src/callbacks.md
- docs/src/index.md
This PR enforces strict mode in the docs
> Make docs strict

- test/integrator.jl
- test/integrator_utils.jl
This PR adds some QA tests for the integrators that we build.
> Add QA tests on built integrators

- test/aqua.jl
This PR fixes the aqua tests and corrects the limits for ambiguities and unbound arguments
> Fix aqua tests

- Project.toml
- src/ClimaTimeSteppers.jl
- src/solvers/newtons_method.jl
- src/solvers/update_signal_handler.jl
This PR re-designs the signal handlers to improve inference.
> Re-design run for signal handlers

- src/integrators.jl
This PR makes the `save_func` not a function of the integrator, which alleviates a circular dependency upon initializing the integrator. A peel off from #115.
> Make save_func not a function of the integrator

- .dev/Manifest.toml
- docs/Manifest.toml
- perf/Manifest.toml
- test/Project.toml
This PR updates the OrdinaryDiffEq compat and updates the dependencies
> Update OrdinaryDiffEq compat

- src/ClimaTimeSteppers.jl
- src/solvers/lsrk.jl
- src/solvers/mis.jl
- src/solvers/ssprk.jl
- src/solvers/wickerskamarock.jl
- test/aqua.jl
This PR fixes the broken aqua tests.
> Fix broken aqua tests

- test/problems.jl
This PR trims some unused incrementing components in the test problems
> Trim incrementing components in test problems

- src/solvers/ark.jl
This PR fixes a few type issues
> Refactor and house cleaning

- docs/refs.bib
- src/solvers/MultirateInfinitesimalGARKDecoupledImplicit.jl
- src/solvers/MultirateInfinitesimalGARKExplicit.jl
- test/ode_tests_convergence.jl
- test/problems.jl
This PR uses the bibliography and reduces some duplicate docs
> Use bib, reduce duplicate docs

- src/ClimaTimeSteppers.jl
- src/solvers/ark.jl
- src/solvers/lsrk.jl
- src/solvers/mis.jl
- src/solvers/multirate.jl
- src/solvers/wickerskamarock.jl
- test/convergence.jl
- test/convergence_orders.jl
- test/convergence_utils.jl
- test/ode_tests_basic.jl
This PR:
- Fixes some bugs, to get more code running
- Un-comments some tests, to increase test coverage
- Refactors, and fixes bugs in, the convergence tabulation
> Increase test coverage

- .github/codecov.yml
- .github/workflows/CodeCov.yml
- README.md
This PR adds coverage GHA, and updates the readme.
> Add coverage GHA

- README.md
- docs/src/dev/report_gen.md
- docs/src/dev/types.md
This PR adds some type hierarchy to the docs
> Add type hierarchy to docs, misc doc fixes

- docs/src/api/algorithms.md
- docs/src/dev/report_gen.jl
- docs/src/plotting_utils.jl
- src/ClimaTimeSteppers.jl
- src/solvers/imex_ark_tableaus.jl
- src/solvers/imex_ssp.jl
- test/convergence.jl
- test/convergence_orders.jl
- test/convergence_utils.jl
- test/utils.jl
This PR adds a sketch for the SSPRK algorithm.
A step towards closing #83.
> Add sketch for ssprk

- .buildkite/pipeline.yml
- perf/flame.jl
This PR updates the flame graph target and adds an allocation test.
> Update flame graph target

- test/problems.jl
This PR qualifies some modules in the test suite
> Qualify some modules in test suite

- .buildkite/pipeline.yml
This PR combines some buildkite commands
> Combine some buildkite commands

- Project.toml
> Bump to v0.7.7

- src/solvers/imex_ark.jl
This PR moves the NVTX range calls outside of the `j`-loops, and uses expressions for the comments.
> Fix NVTX range calls

- src/nl_solvers/newtons_method.jl
- test/aqua.jl
This PR extends (and fixes) the aqua tests
> Extend aqua tests

- src/nl_solvers/newtons_method.jl
- src/solvers/hard_coded_ars343.jl
- src/solvers/imex_ark.jl
This PR adds a hard-coded ARS343 algorithm + NVTX annotations. Supersedes #203
> Hard-code ARS343 + nvtx annotations

- src/solvers/hard_coded_ars343.jl
- src/solvers/imex_ark.jl
This PR reduces the storage of the ARK methods.
> Reduce storage of ark methods

- Project.toml
- perf/flame.jl
- src/solvers/imex_ark.jl
- src/solvers/imex_ssprk.jl
> Re-simplify dispatch, remove hard coded ARS

- Project.toml
- perf/Manifest.toml
- perf/Project.toml
- src/ClimaTimeSteppers.jl
This PR removes CUDA as a direct dependency. Closes #239.
> Remove direct CUDA dependency

- src/integrators.jl
- src/nl_solvers/newtons_method.jl
This PR adds some NVTX annotations to some functions, so that we have more granular profile information. cc @sriharshakandala
I'm going to follow up and try to add ranges, but I want to test that in ClimaAtmos first since [we've had issues with that in the past](https://github.com/CliMA/ClimaTimeSteppers.jl/issues/225)
> NVTX annotate some functions

- src/solvers/imex_ark.jl
- src/utilities/fused_increment.jl
This PR applies the fused incrementing, so that we reduce the number of reads.
> Use fused incrementing

- src/utilities/convergence_condition.jl
- test/integrator_utils.jl
- test/problems.jl
> Fix some warnings

- test/problems.jl
#258 seems to have broken the docs (I thought that our CI was sufficient, but apparently our docs have wider coverage).
This PR is trying to fix it.
> Try to fix docs

- Project.toml
- src/solvers/imex_ssprk.jl
> Hotfix for SSP

- Project.toml
- src/utilities/convergence_condition.jl
> Fix Vararg warning in MultipleConditions struct

- Project.toml
- ext/ClimaTimeSteppersBenchmarkToolsExt.jl
- ext/benchmark_utils.jl
> Make step trial optional

- Project.toml
- ext/ClimaTimeSteppersBenchmarkToolsExt.jl
- src/solvers/rosenbrock.jl
This fixes `n_calls_per_step`, which is broken on main.
> Fix `n_calls_per_step`

- .buildkite/pipeline.yml
This PR makes IMKG254b soft-fail, failure found in this [build](https://buildkite.com/clima/climatimesteppers-ci/builds/1374#0193266c-58f3-4ccd-b03b-635669c2d2e5).
> Make IMKG254b soft-fail

- .buildkite/pipeline.yml
Both seen in #https://buildkite.com/clima/climatimesteppers-ci/builds/1389.
> Mark more jobs as soft-fail

- docs/src/dev/compute_convergence.jl
This PR adds some debug info, to help us know which problems we may want to increase the number of steps (effectively reducing the timestep).
> Add debug to NaNs error

- .buildkite/pipeline.yml
- test/problems.jl
Closes #283, closes #301.
Next we can fix / update initialization (avoiding `similar`) so that this doesn't happen again.
> Fix flaky CI

- docs/src/dev/compute_convergence.jl
> Fix NaN check

- test/problems.jl
> Fix missing dtγ

- docs/src/dev/compute_convergence.jl
- docs/src/dev/summarize_convergence.jl
This PR fixes the convergence plots. Co-authored by @dennisYatunin.
> Fix convergence plots

- .buildkite/Manifest.toml
- Project.toml
- src/ClimaTimeSteppers.jl
Remove `Colors.jl` package as a direct depencency
----
> Remove `Colors.jl` package as a direct depencency

- .buildkite/Manifest.toml
- .dev/Manifest.toml
- Project.toml
- docs/Manifest.toml
- src/nl_solvers/newtons_method.jl
Needed to support Oceananingans 0.96.22
> Update Krylov compat

- NEWS.md
- Project.toml
> Bump to 0.8.5
