test/compare_generated.jl
This PR fixes a broken test (`@test !(integrator.u === not_generated_integrator.u)` was failing), which meant that the comparison was against the same backing data, so the comparison of solutions was not actually valid. Fortunately, the comparison tests are still passing.
I haven't checked, but we should double check that this isn't happening elsewhere (cc @dennisYatunin).
=> Fix broken comparison test

src/solvers/imex_ark.jl, src/solvers/imex_ark_tableaus.jl, test/convergence.jl
This PR fixes a big in the IMEX ARK scheme that was causing the implicit tendency to not be recorded for the last Newton iteration (it was being recorded for the pre-last Newton iteration). It also adds the HOMMEM1 IMEX ARK method, which Oswald asked to have available.
The linear IMEX unit test now only requires one Newton iteration to give the expected convergence orders, whereas before it required 2 (using more iterations does not change the convergence order, as the problem is linear). This should fix some of the issues we've been seeing in ClimaAtmos.
=> Fix bug in IMEXARKAlgorithm, add HOMMEM1

.dev/Manifest.toml, .dev/Project.toml, .dev/up_deps.jl, docs/Manifest.toml, perf/Manifest.toml, test/Project.toml
This PR adds an up-deps script for easing the update of the checked-in manifest files. This script can be run with `julia .dev/up_deps.jl`
=> Add and apply up_deps script

src/integrators.jl, test/integrator.jl
This PR fixes `step!` so that it can be called arbitrarily many times.
Closes #73 
This adds a check for `!isempty(tstops)` to `DiffEqBase.step!` for our `DistributedODEIntegrator`, allowing the integrator to step past the final `tstop`.
=> Fix bug in step! that prefents stepping past t_end

docs/src/newtons_method.md, src/solvers/newtons_method.jl, test/test_newtons_method.jl
This PR adds a `print_condtion_number` option to `KrylovMethod`.
When `print_condtion_number` is `true`, the full Jacobian matrix is materialized before any Krylov iterations occur, and its condition number is printed to the terminal. If a preconditioner is being used, the condition numbers with and without the preconditioner are both printed. Note that this process will usually be slower than the Krylov iterations themselves, so `print_condtion_number` should only be set to `true` for debugging.
----
=> Add print_condition_number option

src/sparse_containers.jl
This PR removes the duplicate type information in the SparseContainers type by requiring the input is an `NTuple`, and then adding
```julia
sc_eltype(::Type{NTuple{N, T}}) where {N, T} = T
sc_eltype(::SparseContainer{SIM, T}) where {SIM, T} = sc_eltype(T)
```
So that we can still retain the eltype information without explicitly storing it.
=> Rm duplicate type information in SparseContainers

src/solvers/newtons_method.jl, src/sparse_containers.jl, test/sparse_containers.jl
This PR takes a couple steps to tackle some latency issues:
- [Avoid UnionAll::DataType in struct](https://github.com/CliMA/ClimaTimeSteppers.jl/commit/52c9ff0cd6c1dc10271023811e626300a1109937), which was shown to improve inference [here](https://github.com/CliMA/Thermodynamics.jl/pull/71), and a smaller MWE [here](https://gist.github.com/charleskawczynski/61efc7b769e14eab7231e686773b9d0e)
- [Allow SparseContainers to work with Arrays](https://github.com/CliMA/ClimaTimeSteppers.jl/commit/c5c53ee37e950384b4cac1b9c11335e76609192a)
=> Prep alleviating latency issues

test/callbacks.jl, test/problems.jl, test/runtests.jl
This PR:
- Deletes unused variables
- Moves the `const_prob_inc` problem into `test/callbacks.jl`
- Moves the callbacks test into a SafeTestsets test, to improve test modularity
=> Move callbacks test into safetestset

docs/src/algorithms.md, perf/flame.jl, perf/jet.jl, test/compare_generated.jl, test/convergence.jl, test/convergence_utils.jl, test/integrator.jl, test/problems.jl, test/runtests.jl, test/utils.jl
This PR:
- Changes the `test/problems.jl` script to instead define functions
- Qualifies some methods
- Moves more tests into safetestsets
- Includes the utility functions only in the portion of the unit tests where needed.
=> Modularize remaining unit tests

.buildkite/pipeline.yml
I noticed a deprecation warning:
```
┌ Warning: The JULIA_MPI_BINARY environment variable is no longer used to configure the MPI binary.
│ Please use the MPIPreferences.jl package instead:
│ 
│     MPIPreferences.use_system_binary()  # use the system binary
│     MPIPreferences.use_jll_binary()     # use JLL binary
│ 
│ See https://juliaparallel.org/MPI.jl/stable/configuration/ for more details
│ 
│   ENV["JULIA_MPI_BINARY"] = "system"
│   MPIPreferences.binary = "MPICH_jll"
└ @ MPI /central/scratch/esm/slurm-buildkite/climatimesteppers-ci/363/depot/cpu/packages/MPI/5cAQG/src/MPI.jl:90
```
I think this PR should fix it.
=> Fix MPI config

src/ClimaTimeSteppers.jl, src/convergence_orders.jl, src/solvers/imex_ark.jl, test/ode_tests_common.jl
This PR adds a theoretic convergence order stub, that we can use per algorithm. This will be nice for users, and for our tests.
=> Add theoretic convergence order func stub

Project.toml, docs/src/algorithms.md, perf/flame.jl, perf/jet.jl, src/ClimaTimeSteppers.jl, src/convergence_orders.jl, src/integrators.jl, src/solvers/imex_ark.jl, src/solvers/imex_ark_tableaus.jl, test/compare_generated.jl, test/convergence.jl, test/single_column_ARS_test.jl, test/utils.jl
This PR:
- Adds a new abstract type `AbstractImexARKAlgorithm <: DistributedODEAlgorithm`
- Adds user-facing types for all of the imex ark algorithms, all of which subtype `AbstractImexARKAlgorithm`
- Defines `theoretical_convergence_order` for these new types
- Adjusts the tests accordingly
This should all help with two things
- Initializing algorithms. One issue we've had in ClimaAtmos is that initializing an algorithm requires first inspecting if an algorithm is a function, in which case assumptions are made about how that function is called. This is really clunky, and usage requires understanding ClimaTimeStepper internals.
- Documentation. Several of these existing "algorithms", are just constants pointing to a generic tableau specific to that algorithm. Documenting these algorithms …
=> Make user-facing types

docs/src/newtons_method.md, src/solvers/imex_ark.jl, src/solvers/newtons_method.jl, src/solvers/update_signal_handler.jl
This PR improves the `update_j` interface, which allows for the Jacobian to be updated at arbitrary times (not just on every Newton iteration). It also slightly cleans up the `KrylovMethod` struct.
- Gives `NewtonsMethod` an `update!` function, which propagates an external `UpdateSignal` to the `update_j` signal handler in `NewtonsMethod`. This interface could potentially be extended to other values in the `NewtonsMethod` cache that we want to update while `NewtonsMethod` is not running. The new functionality is described in the documentation for `NewtonsMethod`.
- Replaces the value of `a_imp[end, end]` in `step_u!`'s manual Jacobian update with `γ`, which is either the unique non-zero value along the diagonal of `a_imp` or `nothing` if no such value exists. If the user specifies that …
=> Clean up update_j and KrylovMethod

.buildkite/pipeline.yml
This PR adds the use of the Julia depot path, to speed up CI times.
I've also disabled the gpu env, since this seems to be needed to be built serially and it's not currently being used.
=> Use julia depot path in buildkite, disable gpu env

.buildkite/pipeline.yml, perf/benchmark.jl
This PR adds the benchmark back into CI, removed in #105. This script just prints the results of `@benchmark` for a couple problems
=> Add benchmark back into CI

Project.toml, src/sparse_containers.jl, test/aqua.jl, test/sparse_containers.jl
This PR fixes inference for SparseContainers, as seen in the flame graph. A step towards #103.
This PR also bumps the minor version for a new release
=> Fix SparseContainers inference

src/solvers/convergence_checker.jl, src/solvers/imex_ark.jl, src/solvers/newtons_method.jl, test/test_convergence_checker.jl, test/test_newtons_method.jl
This PR decomposes `run!` into `check_convergence!`, `jvp!` `get_rtol!`, `solve_krylov!`
Next, we should remove the `run!` fallback (i.e., fix #118)
=> Decompose run!

.buildkite/pipeline.yml, src/solvers/newtons_method.jl
This PR adds a JET test and fixes the failures by making the `verbose` option a compile-time constant.
=> Add and fix JET test

src/solvers/imex_ark.jl
This PR fixes the cache allocation when `T_imp!` is `nothing`, a peel off from #115.
=> Do not allocate T_imp cache if nothing

perf/benchmark.jl, perf/flame.jl, perf/jet.jl, src/integrators.jl, src/solvers/ark.jl, src/solvers/imex_ark.jl, src/solvers/lsrk.jl, src/solvers/mis.jl, src/solvers/multirate.jl, src/solvers/rosenbrock.jl, src/solvers/ssprk.jl, src/solvers/wickerskamarock.jl
This PR renames the `cache` method to `init_cache`, peeled off from #26.
=> Rename cache method to init_cache

src/solvers/ark.jl, src/solvers/lsrk.jl, src/solvers/mis.jl, src/solvers/multirate.jl, src/solvers/rosenbrock.jl, src/solvers/ssprk.jl, src/solvers/wickerskamarock.jl
This PR applies a few refactoring changes:
- Changes syntax `a = x.a` to `(; a) = x` for several variables
- Adds a `n_stages` method for some caches
- Renames `nstages` to `n_stages`
=> Refactor, unpack efficiently, unify n_stages nstages

docs/src/algo_comparisons.jl, docs/src/plotting_utils.jl, test/convergence.jl, test/convergence_utils.jl, test/problems.jl, test/utils.jl
This PR refactors the tests a bit, to prep for making algorithms tableau-aware, so that we can extend `OrdinaryDiffEq`'s `alg_order`.
=> Refactor tests, prep for tab-aware alg

docs/src/plotting_utils.jl, test/convergence_utils.jl, test/utils.jl
This PR changes maxiter to 2 for all cases, so that we disentangle the alg prescription from the problem
=> Always use maxiter = 2

src/ClimaTimeSteppers.jl, src/functions.jl, src/solvers/imex_ark.jl, src/solvers/imex_ark_tableaus.jl
This PR:
- Moves `ClimaODEFunction` into `functions.jl`
- Renames `make_IMKGAlgorithm ` to `make_IMKGTableau`
- Moves the export for `AbstractIMEXARKTableau` into the same file its defined
=> Cleanup and fix names

docs/Manifest.toml, docs/Project.toml, docs/src/test_problems/diffusion_2d.md, perf/Manifest.toml, perf/Project.toml, test/problems.jl
This PR
- Adds the diffusion test problems. (a peel off from #115)
- Updates the dependencies
=> Add diffusion test problems

Project.toml, docs/src/api/algorithms.md, docs/src/dev/report_gen.jl, docs/src/dev/types.md, perf/benchmark.jl, perf/flame.jl, perf/jet.jl, src/ClimaTimeSteppers.jl, src/solvers/imex_ark.jl, src/solvers/imex_ssp.jl, src/solvers/imex_tableaus.jl, test/convergence_orders.jl, test/convergence_utils.jl, test/single_column_ARS_test.jl, test/utils.jl
This PR renames several data structures in preparation for the "mode" changes outlined in #151.
- `AbstractTableau` -> `AbstractAlgorithmName`
- `AbstractARKTableau` -> `ARKAlgorithmName`
- `AbstractSSPRKTableau` -> `SSPRKAlgorithmName`
- `tabname` -> `algorithm_name`
- `IMEXARKTableau` -> `IMEXTableaus`
- `tableau` -> `IMEXTableaus`
- `make_IMKGTableau` -> `IMKGTableaus`
- `imex_ark_tableaus.jl` -> `imex_tableaus.jl`
- Rearrange a few lines in the docs
- Make the inner `IMEXARKAlgorithm` constructor into an outer constructor (will be needed later when combining this with the `IMEXSSPRKAlgorithm` constructor)
----
=> Rename "Tableau"s to "AlgorithmName"s

Project.toml, docs/Manifest.toml, perf/Manifest.toml, src/ClimaTimeSteppers.jl, src/nl_solvers/newtons_method.jl, test/Project.toml
This PR changes from using `Krylov.ktypeof` to `ClimaComms.array_type` to determine the array type passed to Krylov.jl
=> Use ClimaComms to determine array type

docs/refs.bib, docs/src/api/ode_solvers.md, docs/src/plotting_utils.jl, src/solvers/explicit_tableaus.jl
ClimaLSM.jl wants to use the RK4 explicit algorithm, so we should implement it here.
Closes #183
----
=> add RK4 explicit tableau

src/nl_solvers/newtons_method.jl, src/solvers/imex_ark.jl, src/solvers/imex_ssprk.jl
This PR hoists the check for when gamma is nothing.
I think it's just clearer what's happening if we inline `update!`.
=> Inline `update!` and hoist gamma check

bors.toml
This PR temporarily disables requiring a pass check from buildkite. We can add this back in next week when caltech central is back online.
=> Temporarily disable buildkite

src/nl_solvers/newtons_method.jl, src/solvers/imex_ark.jl, src/solvers/imex_ssprk.jl, src/utilities/update_signal_handler.jl
This PR unifies the signal handlers and their caches-- I think having them split just complicated the `needs_update!` interface.
=> Simplify signal handlers

Project.toml, src/solvers/imex_ark.jl, src/solvers/imex_ssprk.jl
This PR will allow us to overload custom implementations of `step_u!` based on the algorithm name (e.g., `ARS343`). This is a non-breaking change, so we can experiment with the time stepping in ClimaAtmos and port here once we finalize the form.
=> Allow for specializing on the algorithm name (type)

Project.toml, bors.toml, perf/flame.jl, src/functions.jl, src/integrators.jl, src/nl_solvers/newtons_method.jl, src/solvers/hard_coded_ars343.jl
This PR adds `post_explicit!` and `post_implicit!` callback hooks to ClimaODEFunction, which do nothing by default, and calls to functions were added in the ARS343`step_u!`. Should we bother calling these functions in the generic callback? cc @simonbyrne 
I spoke with @simonbyrne about this, and he'll add these into https://github.com/CliMA/ClimaTimeSteppers.jl/pull/212 once we are happy with a version that is simpler to reason about.
=> Add post callbacks

Project.toml
We accidentally skipped version 0.8 (so 0.9 was never registered as I had intended).
=> Correct patch version

src/nl_solvers/newtons_method.jl, src/utilities/convergence_checker.jl, test/test_convergence_checker.jl
This PR reorders the newton solver, to ensure that we always end in post implicit callback.
On the main branch, it's possible that `check_convergence!` returns true on `n=0`, resulting in a break before the post implicit callback is called.
I've also renamed `check_convergence!` to `is_converged!`
=> Improve names, reorder newton solver

Project.toml, docs/src/plotting_utils.jl, src/functions.jl, src/solvers/imex_ark.jl, src/solvers/imex_ssprk.jl
This PR defines `AbstractClimaODEFunction`, so that we can, from ClimaAtmos, define our own `AtmosODEFunction` with custom hooks (post stage callback etc.) and rearrange them in a custom `step_u!`.
=> Define AbstractClimaODEFunction

Project.toml, src/nl_solvers/newtons_method.jl, src/solvers/imex_ark.jl, src/solvers/imex_ssprk.jl
I think [the ClimaAtmos branch](https://github.com/CliMA/ClimaAtmos.jl/pull/2175) is getting close to covering all of the edge cases, so I think it's a good time to start incorporating the post-callback fixes into ClimaTimeSteppers. The edge cases that we missed included:
- Accounting for when `!isnothing(T_imp!) && !iszero(a_imp[i, i])` is false
- Krylov evaluations of `f!` (`T_imp!`) with something other than `U`/`x`-- which requires an additional `post_implicit!` call
- Calling `post_explicit!(U, p, t_imp)` instead of `post_explicit!(U, p, t_exp)`, and doing this _after_ `temp` is computed (to preserve the existing behavior).
- Finally, computing `T_imp` using the `U` from _before_ the `post_implicit!` call, which requires injecting this into the callback (we add two closures to avoid …
=> Callback fixes

Project.toml, src/solvers/imex_ark.jl, src/solvers/imex_ssprk.jl
This PR
- Adds `post_explicit!` calls to end of step
- Removes nvtx range macros, since they seem to be blowing up memory requirements (example build here: https://buildkite.com/clima/climaatmos-ci/builds/13552)
=> Add `post_explicit!` call to end of step, rm nvtx range macros

Project.toml, src/solvers/imex_ark.jl, src/solvers/imex_ssprk.jl
This PR removes extraneous dss calls. Tested out in https://buildkite.com/clima/climaatmos-ci/builds/13595, results look like they've only changed by machine precision.
=> Remove extraneous `dss!` and `post_explicit!` calls

src/solvers/imex_ark.jl
While working on the limiters, it occurred to me that when we have limiters with `i = 1` in the ARK method:
```julia
@. U = u
for j in 1:(i - 1)
iszero(a_exp[i, j]) && continue
@. U += dt * a_exp[i, j] * T_lim[j]
end
lim!(U, p, t_exp, u)
```
we have 
```julia
@. U = u
lim!(U, p, t_exp, u)
```
and I think that, since `u` is just a copy of `U`, `lim!(U, p, t_exp, u)` will do nothing (based on the existing implementation with automatically computing bounds). Therefore, we can eliminate this call (for `i = 1`).
Doing this optimization of course assumes that `lim!(U, p, t_exp, U)` does nothing, and this will be wrong if later we decide that it should do something. However, it's not clear to me that we will need to/want to change it.
=> Eliminate a call to `lim!`

src/integrators.jl
This PR adds NVTX ranges to the callbacks, so that we have callback-by-callback granularity from the timestepper (the names will just be numbered at this level), but we can also add annotations to the Atmos callbacks, so that we can appropriately name them.
=> Add nvtx range to callbacks

test/integrator.jl, test/integrator_utils.jl
This PR fixes and renames `has_DataType_or_UnionAll`.
=> Fix and rename has_DataType_or_UnionAll

src/ClimaTimeSteppers.jl, src/solvers/explicit_tableaus.jl, src/solvers/imex_ssprk.jl, src/solvers/imex_tableaus.jl, src/utilities/fused_increment.jl, src/utilities/sparse_coeffs.jl, test/fused_increment.jl, test/runtests.jl
This PR adds support for fused incrementing of the state vector for the explicit and imex tableaus. We can easily extend it to the other tableaus, but I've only applied it to these for now.
Fused incrementing is supported by adding a new type: `MaskedCoeffs`, which has a simple definition:
```julia
struct MaskedCoeffs{S, m, C}
coeffs::C
function MaskedCoeffs(coeffs::C) where {C}
m = BitArray(iszero.(coeffs))
return new{size(m), Tuple(m), C}(coeffs)
end
end
```
Most behavior of these masks simply forward to the `coeffs`, however, there is a special supported feature: the bit array, which indicates whether the coefficients are zero / skippable or not, are converted to tuples, and retrievable at compile-time:
```julia
Base.@propagate_inbounds Base.getindex(::Type{MaskedCoeffs{S, m, C}}, …
```
=> Add support for fused incrementing

src/utilities/fused_increment.jl
This PR changes `fused_increment` to use recursion instead of a generated function. I think this partially addresses #251
=> Use recursion instead of generated function

src/ClimaTimeSteppers.jl, src/functions.jl, src/solvers/compute_T_exp_T_lim.jl, src/solvers/imex_ark.jl, src/solvers/imex_ssprk.jl
This PR peels off a piece of #229, and will allow us to define a CUDA extension for `compute_T_exp_T_lim!`
=> Allow commscontext input, def compute_T_exp_T_lim

.dev/Manifest.toml, Project.toml, docs/Manifest.toml, docs/src/dev/report_gen.jl, docs/src/plotting_utils.jl, perf/Manifest.toml, test/Project.toml, test/callbacks.jl, test/problems.jl
This PR bumps the ClimaComms compat, and upgrades the allowable dependencies. This should just work when we release a new version of ClimaCore, coming next.
=> Bump ClimaComms compat

src/utilities/convergence_condition.jl
Fixes:
```
┌ ClimaTimeSteppers
│  WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
│  You may need to write `f(x::Vararg{T})` rather than `f(x::Vararg{<:T})` or `f(x::Vararg{T}) where T` instead of `f(x::Vararg{T} where T)`.
```
=> Fix Vararg warning

Project.toml, ext/ClimaTimeSteppersBenchmarkToolsExt.jl, ext/benchmark_utils.jl
This PR allows us to not crop the profile table in `benchmark_step`.
=> Add option to not crop table

ext/ClimaTimeSteppersBenchmarkToolsExt.jl, ext/benchmark_utils.jl
This will allow us to target specific benchmarks. We could eliminate the percentage table, but I think that's more work than it's worth. Instead I've added a warning print that the percentage column is only based off of functions specified in the `only` argument.
=> Allow benchmark_step to benchmark targeted functions

Project.toml, ext/ClimaTimeSteppersBenchmarkToolsExt.jl, ext/benchmark_utils.jl
See https://github.com/ronisbr/PrettyTables.jl/issues/11#issuecomment-2145550354. As a result, we see virtually no information in the method name.
I think 168 should be a good number for buildkite, but the default should probably just use `displaysize`, as this works nice locally.
=> Add horizontal cropping to perf table

Project.toml, docs/src/plotting_utils.jl, src/solvers/rosenbrock.jl
This PR fixes a bug in the Rosenbrock timestepper that results in inconsistent precomputed quantities in ClimaAtmos.
Since the first stage of an `s`-stage timestepping scheme is typically the same as the final state of the previous timestep, we can chose to update `p` based on each of the stages `U_1--U_s`, or we can choose to update it based on the stages `U_2--U_s` and the final state `u`. The Rosenbrock timestepper is currently using the first option, whereas the ARK methods use the second option. With the first option, the value of `p` between timesteps is not consistent with the value of `u`, since it did not get updated when `u` was computed and still has the value from `U_s` (for FSAL timesteppers, `u = U_s`, but SSPKnoth is not FSAL). The second option fixes this issue, so the …
=> Fix consistency of precomputed quantities for Rosenbrock

Project.toml, src/solvers/rosenbrock.jl
This PR fixes some type instabilities, and makes the `RosenbrockTableau` fields concretely typed.
Found in https://buildkite.com/clima/climaatmos-ci/builds/20495#0191e6bb-8f3f-4c0e-b74c-27bb4170f8da (where I've added `@test_opt SciMLBase.step!(integrator)` to the ClimaAtmos driver).
=> Fix type instabilities in Rosenbrock `step_u!`

Project.toml, src/solvers/rosenbrock.jl
I forgot that we always use Float64 for our coefficients,, so the main branch is breaking for float32 simulations. This PR fixes this by allowing for type promotions. Inference should still be fixed by the previous PR, the main issue there was not having `init`, and lack of concrete types in the tableau.
I tested this locally and it works, merging.
=> Allow mixed types for Rosenbrock coeffs

Project.toml, src/integrators.jl
To (hopefully) fix:
```
JET-test failed at /central/scratch/esm/slurm-buildkite/climaatmos-ci/20549/climaatmos-ci/perf/jet_report_nfailures.jl:53
--
  | Expression: #= /central/scratch/esm/slurm-buildkite/climaatmos-ci/20549/climaatmos-ci/perf/jet_report_nfailures.jl:53 =# JET.@test_opt SciMLBase.step!(integrator)
  | ═════ 1 possible error found ═════
  | ┌ step!(integrator::ClimaTimeSteppers.DistributedODEIntegrator{…}) @ ClimaTimeSteppers /central/scratch/esm/slurm-buildkite/climaatmos-ci/depot/default/packages/ClimaTimeSteppers/KGEKL/src/integrators.jl:203
  | │┌ __step!(integrator::ClimaTimeSteppers.DistributedODEIntegrator{…}) @ ClimaTimeSteppers /central/scratch/esm/slurm-buildkite/climaatmos-ci/depot/default/packages/ClimaTimeSteppers/KGEKL/src/integrators.jl:250
  | ││ runtime …
```
=> Add Bool assertion in callback loop

perf/jet.jl
This PR adds a broken JET test for inference an failure in our callbacks loop.
=> Add broken test for inference failure in callbacks loop

Project.toml, perf/jet.jl, src/integrators.jl
This PR fixes the broken inference test for the callback loop. Closes #316 and #315.
=> Fix inference failure in callbacks

docs/src/plotting_utils.jl
This PR is an attempt to prevent the limiters summary table from being cropped:
=> Do not crop limiters table

test/convergence_lsrk.jl, test/tabulate_convergence_orders_imex_ark.jl, test/tabulate_convergence_orders_imex_ssp.jl, test/tabulate_convergence_orders_multirate.jl, test/tabulate_convergence_orders_rosenbrock.jl
The test suite on GHA has a bunch of errors:
```julia
WARNING: Method definition kwcall(NamedTuple{names, T} where T<:Tuple where names, typeof(##232.test_convergence_order!), Any, Any) in module ##232 at /home/runner/work/ClimaTimeSteppers.jl/ClimaTimeSteppers.jl/test/convergence_utils.jl:57 overwritten on the same line (check for duplicate calls to `include`).
WARNING: Method definition kwcall(NamedTuple{names, T} where T<:Tuple where names, typeof(##232.test_convergence_order!), Any, Any, Any) in module ##232 at /home/runner/work/ClimaTimeSteppers.jl/ClimaTimeSteppers.jl/test/convergence_utils.jl:57 overwritten on the same line (check for duplicate calls to `include`).
WARNING: Method definition pass_conv(Any, Any) in module ##232 at …
```
=> Conditionally load convergence utils

.buildkite/pipeline.yml
This PR removes the buildkite `wait` and instead uses `depends_on` using `group` keys, so that the convergence summaries can start before the limiters analysis finishes.
=> Remove buildkite wait and use depends_on

.buildkite/Manifest.toml
This PR fixes the buildkite environment to _dev_ CTS. Praying this isn't an issue. If it is, the parallelization PR is still safe, we may just need to revert back to https://github.com/CliMA/ClimaTimeSteppers.jl/commit/9c286d4a84165599c9f5394699bdabe668d00c73
=> Dev from buildkite env

src/solvers/multirate.jl
Alternatively, the compat for SciMLBase can be restricted. I opened PR #343 to test CI with that.
fixes #341 
SciMLBase.remake is called twice during the cache initialization for a problem with the multirate alg.
SciMLBase changed the way remake(::AbstractODEProblem,...) works in 2.68.0. Previously, if the `f` kwarg was an AbstractODEFunction, the problem was remade with f directly as its function. After 2.68.0, remake(::AbstractODEProblem) calls a new remake method with `f` and `prob.f` as arguments. This new function returns an AbstarctSciMLFunction of the same type and properties as `prob.f`.
This commit replicates the behavior of DiffEqBase.remake on the provided arguments before the change.
----
=> Remake problem manually during multirate init

.buildkite/Manifest.toml, Project.toml, docs/Manifest.toml, src/solvers/hard_coded_ars343.jl, src/solvers/imex_ark.jl, src/solvers/imex_ssprk.jl, src/solvers/rosenbrock.jl
This PR moves the DSS operation from the middle of each implicit stage (between the partial stage assembly and the start of Newton's method) to the end of each implicit stage. The change is applied consistently to all algorithms, and it ensures that stage values passed to our explicit and limited tendencies are always continuous across element boundaries.
The minor version number is also incremented so that we can immediately test this out in ClimaAtmos.
For all simulations on a sphere, our metric terms (`J` and `g`) are discontinuous across element boundaries. Since the implicit tendency uses these metric terms, it introduces discontinuities to the Runge-Kutta stages. To avoid these discontinuities when evaluating explicit and limited tendencies, we must apply DSS after the last …
=> Move DSS to the end of each implicit stage

src/nl_solvers/newtons_method.jl
This is a followup to #346, which missed a `similar` call.
=> similar -> zero

Project.toml, docs/src/api/ode_solvers.md, ext/ClimaTimeSteppersBenchmarkToolsExt.jl, src/functions.jl, src/integrators.jl, src/nl_solvers/newtons_method.jl, src/solvers/hard_coded_ars343.jl, src/solvers/imex_ark.jl, src/solvers/imex_ssprk.jl, src/solvers/rosenbrock.jl, test/problems.jl
This PR undoes a small change that was accidentally introduced in #348. We were previously approximating the implicit tendency as `(U_after_implicit_solve - U_before_implicit_solve) / (Δt * γ)`, but in that PR I ended up changing it to `(DSS(U_after_implicit_solve) - U_before_implicit_solve) / (Δt * γ)`. In the absence of roundoff error, these would be exactly identical. Unfortunately, we do not satisfy `DSS(DSS(U)) == DSS(U)` at a discrete level, so they are not quite identical. Reverting to the original approximation of `T_imp` might marginally improve stability.
**Update:** After testing this change with AMIP, we have found that the original call to DSS before the implicit solve (which was removed in #348) is still necessary, even if we fix the approximation of `T_imp`. Without this …
=> Add DSS before implicit solve, fix T_imp approximation and callbacks

Project.toml, src/solvers/imex_ark.jl, src/solvers/imex_ssprk.jl
This PR swaps the order of DSS and the approximation of `T_imp` to improve the stability of a test case in ClimaAtmos, and it bumps the minor version number.
In #352, I moved the approximation of `T_imp` to just before the second call to DSS, ensuring that the implicit tendency passed to future stages does not include any effects of DSS. This seemed like the correct choice at the time, but further testing with the ClimaAtmos longruns ([T_imp before DSS](https://buildkite.com/clima/climaatmos-gpulongruns/builds/479) vs [DSS before T_imp](https://buildkite.com/clima/climaatmos-gpulongruns/builds/481)) has shown that it is better to have DSS before the approximation of `T_imp`, so that the implicit tendency passed to future stages is always continuous.
----
=> Swap DSS and T_imp approximation

src/solvers/hard_coded_ars343.jl, src/solvers/imex_ark.jl, src/solvers/imex_ssprk.jl
This PR fixes the hard-coded ARS343 timestepper, which I didn't update correctly in #352 and #356. (We should probably add convergence tests for it at some point.) It also simplifies the way we call Newton's method, and it adds some code comments to clarify how we are combining DSS, cache updates, and the implicit solver.
----
=> Fix hard-coded ARS343, simplify code and add comments

NEWS.md, docs/src/tutorials/diffusion.jl, src/integrators.jl, test/integrator.jl
We do this because for long runs, you might want to change the type of time (e.g. ITime) which may not be a number.
=> Remove check for number in tstops_and_saveat_heaps

NEWS.md, Project.toml, src/ClimaTimeSteppers.jl, src/arbitrary_number_types.jl, src/integrators.jl, src/solvers/imex_ark.jl, src/solvers/rosenbrock.jl, src/utilities/fused_increment.jl
This PR adds support for ITime in ARS343 and SSPKnoth. This PR should be merged in after [PR#347](https://github.com/CliMA/ClimaTimeSteppers.jl/pull/347). 
See this [issue](https://github.com/CliMA/ClimaUtilities.jl/issues/145) in ClimaUtilities for the remaining PRs to merge for ITime.
=> Add support for ITime in IMEXAlgorithms and SSPKnoth

release_policy.md
This PR adds a release policy to ClimaTimeSteppers, as recently discussed.
Should we expand on this?
=> Add release policy
